### ISSUE TITLE
Update for Inkscape 1.0

### ISSUE THREAD

**Issue by jmb** [Klowner/inkscape-applytransforms#21]
There are some deprecated functions and dependencies.

After removing the deprecated dependencies from applytransforms.inx (as per http://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0) so that the extension will run, I get the following errors. The first few are easy enough to fix, but I haven't picked through the rest just yet!

```
applytransform.py:115: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
applytransform.py:21: DeprecationWarning: Effect.getselected has been removed
  self.getselected()
applytransform.py:23: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  if self.selected:
applytransform.py:27: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  self.recursiveFuseTransform(self.document.getroot(), parseTransform(None))
applytransform.py:66: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  transf = composeTransform(transf, parseTransform(node.get("transform", None)))
applytransform.py:66: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transf = composeTransform(transf, parseTransform(node.get("transform", None)))
applytransform.py:103: DeprecationWarning: simpletransform.formatTransform -> str(Transform(mat))
  node.set('transform', formatTransform(transf))
applytransform.py:75: DeprecationWarning: cubicsuperpath.parsePath -> None
  p = cubicsuperpath.parsePath(d)
Traceback (most recent call last):
  File "applytransform.py", line 115, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated.py", line 181, in affect
    return self.run(args=args)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 111, in run
    self.save_raw(self.effect())
  File "applytransform.py", line 27, in effect
    self.recursiveFuseTransform(self.document.getroot(), parseTransform(None))
  File "applytransform.py", line 110, in recursiveFuseTransform
    self.recursiveFuseTransform(child, transf)
  File "applytransform.py", line 110, in recursiveFuseTransform
    self.recursiveFuseTransform(child, transf)
  File "applytransform.py", line 75, in recursiveFuseTransform
    p = cubicsuperpath.parsePath(d)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated.py", line 258, in _inner
    return func(*args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated-simple/cubicsuperpath.py", line 37, in parsePath
    return paths.CubicSuperPath(paths.Path(d))
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/paths.py", line 1014, in __init__
    for item in (path_d or ()):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/paths.py", line 1027, in parse_string
    args = list(strargs(numbers))
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/utils.py", line 169, in strargs
    return [kind(val) for val in string.replace(',', ' ').split()]
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/utils.py", line 169, in <listcomp>
    return [kind(val) for val in string.replace(',', ' ').split()]
ValueError: could not convert string to float: '0-497'
```

**Comment by msdobrescu** [comment]
Hi, my question too.

Could it be replaced by the following?

`from inkex.paths import CubicSuperPath

...

CubicSuperPath(node)`

**Comment by IHaveThatPower** [comment]
I have updated the extension in a fork to work with Inkscape 1.0+ and intiated a pull request on this repo to merge the update in, at @Klowner 's convenience if approved:

https://github.com/Klowner/inkscape-applytransforms/pull/25

**Comment by Dev-iL** [comment]
@msdobrescu Thanks for the tip, that worked for me! Is `inkex.paths.CubicSuperPath(...)` the undeprecated form of `cubicsuperpath.parsePath(...)`? If so - how did you know that?

**Comment by msdobrescu** [comment]
I remember looking in the docs related to extensions deprecation, starting from here: https://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0

**Comment by Klowner** [comment]
3c0b9bd should work happily with Inkscape 1.0+

**Comment by carlinmack** [comment]
Hi, sorry about this but why isn't the extension showing in the menu?
![image](https://user-images.githubusercontent.com/6676843/89109052-c438b180-d40b-11ea-9ebd-ed11a4c58e7b.png)
Inkscape was not opened until after pasting the files there
