### ISSUE TITLE
str() casting in Path

### ISSUE THREAD

**Issue by vmario89** [Klowner/inkscape-applytransforms#37]
Hi,

i created a new inkscape extension which is calling ApplyTransform class externally to do some cool stuff. This works fine for most things but it seems there is some small hidden error which was was able to fix by simply adding a str() cast. i am asking if you could add this to that repo. the explanation:

```
/home/tomate/.local/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py:142: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  return original_import(name, *args, **kwargs)
Traceback (most recent call last):
  File "vpypetools.py", line 200, in <module>
    vpypetools().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 141, in run
    self.save_raw(self.effect())
  File "vpypetools.py", line 184, in effect
    applytransform.ApplyTransform().recursiveFuseTransform(shape) 
  File "../applytransform.py", line 156, in recursiveFuseTransform
    self.recursiveFuseTransform(child, transf)
  File "../applytransform.py", line 75, in recursiveFuseTransform
    node.set('d', Path(CubicSuperPath(p).to_path()))
  File "src/lxml/etree.pyx", line 816, in lxml.etree._Element.set
  File "src/lxml/apihelpers.pxi", line 593, in lxml.etree._setAttributeValue
  File "src/lxml/apihelpers.pxi", line 1538, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'Path'
```

the external call i did was

```
...
applyTransformAvailable = False

...

        # at first we apply external extension
        try:
            sys.path.append("..") # add parent directory to path to allow importing applytransform (vpype extension is encapsulated in sub directory)
            import applytransform
            applyTransformAvailable = True
        except Exception as e:
            # inkex.utils.debug(e)
            inkex.utils.debug("Calling 'Apply Transformations' extension failed. Maybe the extension is not installed. You can download it from official InkScape Gallery. Skipping this step")

...

        if self.options.apply_transformations and applyTransformAvailable:
            for shape in self.svg.selection:
                applytransform.ApplyTransform().recursiveFuseTransform(shape) 
```

i changed the line 75 from
```
            node.set('d', Path(CubicSuperPath(p).to_path())
```
to
```
            node.set('d', str(Path(CubicSuperPath(p).to_path()))
```

now this works perfectly

**Comment by Klowner** [comment]
How's that?

**Comment by vmario89** [comment]
hey. that helps a lot. thank you! :-)
