### ISSUE TITLE
Failure to transform some paths

### ISSUE THREAD

**Issue by jtojnar** [Klowner/inkscape-applytransforms#40]
For some SVGs the extension fails with the following error:

```pytb
Traceback (most recent call last):
  File "applytransform.py", line 159, in <module>
    ApplyTransform().run()
  File "/nix/store/ahn6z9yjrwh8b12c1cxn77ydhym9l50c-inkscape-with-extensions-1.1/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "applytransform.py", line 25, in effect
    self.recursiveFuseTransform(self.document.getroot())
  File "applytransform.py", line 156, in recursiveFuseTransform
    self.recursiveFuseTransform(child, transf)
  File "applytransform.py", line 156, in recursiveFuseTransform
    self.recursiveFuseTransform(child, transf)
  File "applytransform.py", line 156, in recursiveFuseTransform
    self.recursiveFuseTransform(child, transf)
  [Previous line repeated 1 more time]
  File "applytransform.py", line 73, in recursiveFuseTransform
    p = CubicSuperPath(d)
  File "/nix/store/ahn6z9yjrwh8b12c1cxn77ydhym9l50c-inkscape-with-extensions-1.1/share/inkscape/extensions/inkex/paths.py", line 1450, in __init__
    items = Path(items)
  File "/nix/store/ahn6z9yjrwh8b12c1cxn77ydhym9l50c-inkscape-with-extensions-1.1/share/inkscape/extensions/inkex/paths.py", line 1173, in __init__
    for item in (path_d or ()):
  File "/nix/store/ahn6z9yjrwh8b12c1cxn77ydhym9l50c-inkscape-with-extensions-1.1/share/inkscape/extensions/inkex/paths.py", line 1188, in parse_string
    args = list(strargs(numbers))
  File "/nix/store/ahn6z9yjrwh8b12c1cxn77ydhym9l50c-inkscape-with-extensions-1.1/share/inkscape/extensions/inkex/utils.py", line 167, in strargs
    return [kind(val) for val in string.replace(',', ' ').replace('-', ' -').replace('e ', 'e').replace('E ','e').split()]
  File "/nix/store/ahn6z9yjrwh8b12c1cxn77ydhym9l50c-inkscape-with-extensions-1.1/share/inkscape/extensions/inkex/utils.py", line 167, in <listcomp>
    return [kind(val) for val in string.replace(',', ' ').replace('-', ' -').replace('e ', 'e').replace('E ','e').split()]
ValueError: could not convert string to float: '-16.43.12'
```

**Comment by jtojnar** [comment]
Turns out inkex does not support the path syntax fully. I opened https://gitlab.com/inkscape/extensions/merge_requests/342 to fix that.
