### ISSUE TITLE
TypeError: operand types

### ISSUE THREAD

**Issue by QuinnFreedman** [Klowner/inkscape-applytransforms#67]
When I run the extension, I get the following error:

```
Traceback (most recent call last):
  File "~/.config/inkscape/extensions/applytransform.py", line 154, in <module>
    ApplyTransform().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "~/.config/inkscape/extensions/applytransform.py", line 23, in effect
    self.recursiveFuseTransform(shape)
  File "~/.config/inkscape/extensions/applytransform.py", line 60, in recursiveFuseTransform
    transf = Transform(transf) @ Transform(node.get("transform", None))
TypeError: unsupported operand type(s) for @: 'Transform' and 'Transform'
```

**Comment by jtojnar** [comment]
Do you have Inkscape [1.2 or later](https://gitlab.com/inkscape/extensions/-/commit/648f560558f1e961f8b44f7b267354ec4782c83c)? If not, you will need to use older version of this extension (before https://github.com/Klowner/inkscape-applytransforms/commit/0b9dfc0365ab9cfeca4c1351d7cbfda4a454051a).

**Comment by QuinnFreedman** [comment]
That was the issue, thanks
